"""create exam_details table

Revision ID: 427683f077ed
Revises: 94b53e6063be
Create Date: 2024-01-02 19:26:08.643071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '427683f077ed'
down_revision: Union[str, None] = '94b53e6063be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam_details',
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('class_id', sa.Integer(), nullable=False),
    sa.Column('exam_fees', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['class_id'], ['std_classes.class_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['exam_id'], ['exams.exam_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.session_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exam_id', 'session_id', 'class_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_details')
    # ### end Alembic commands ###
